title: Роголев Дмитрий Александрович
tagline: Fullstack web-разработчик.
description: Fullstack web-разработчик.
theme: jekyll-theme-hacker
github:
    repository_url: https://github.com/dmitry-rogolev

lang: ru-RU
timezone: Asia/Novosibirsk

defaults:
    - scope:
          path: ''
          type: 'pages'
      values:
          layout: 'default'
